export const YOUTUBE_VIDEOS_API =
    "https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&regionCode=US&maxResults=30&key=";

// sample response (YouTube API)
export const YOUTUBE_SAMPLE_RESPONSE = {
    kind: "youtube#videoListResponse",
    etag: "JwKE6uaj1oKpgfIYOEYaQl7hnNU",
    items: [
        {
            kind: "youtube#video",
            etag: "daI_wiFIqH4agpG3eDYN1PSyzYk",
            id: "vKkoBUPav3s",
            snippet: {
                publishedAt: "2024-01-29T05:03:51Z",
                channelId: "UC3jOd7GUMhpgJRBhiLzuLsg",
                title: "Nicki Minaj - Big Foot (Official Audio)",
                description:
                    'Official audio for Nicki Minaj "Big Foot", available everywhere now: https://NickiMinaj.lnk.to/BigFoot\n\n►Connect with Nicki 🎀🦄\nhttps://www.nickiminajofficial.com\nhttps://instagram.com/nickiminaj\nhttps://twitter.com/nickiminaj\nhttps://facebook.com/nickiminaj\nhttps://snapchat.com/add/nickiminaj\nhttps://tiktok.com/@nickiminaj\n\n►Shop Official Merch: https://shop.nickiminajofficial.com\n\n►Subscribe on YouTube: http://bit.ly/NickiMinajYTSub\n\n#NickiMinaj #BigFoot',
                thumbnails: {
                    default: { url: "https://i.ytimg.com/vi/vKkoBUPav3s/default.jpg", width: 120, height: 90 },
                    medium: { url: "https://i.ytimg.com/vi/vKkoBUPav3s/mqdefault.jpg", width: 320, height: 180 },
                    high: { url: "https://i.ytimg.com/vi/vKkoBUPav3s/hqdefault.jpg", width: 480, height: 360 },
                    standard: { url: "https://i.ytimg.com/vi/vKkoBUPav3s/sddefault.jpg", width: 640, height: 480 },
                    maxres: { url: "https://i.ytimg.com/vi/vKkoBUPav3s/maxresdefault.jpg", width: 1280, height: 720 },
                },
                channelTitle: "Nicki Minaj",
                tags: [
                    "nicki",
                    "minaj",
                    "nicki minaj",
                    "pink friday",
                    "young money",
                    "The Pink Print",
                    "Pink Print",
                    "big foot",
                    "nicki minaj big foot",
                    "nicki minaj beef",
                    "hip hop",
                ],
                categoryId: "10",
                liveBroadcastContent: "none",
                localized: {
                    title: "Nicki Minaj - Big Foot (Official Audio)",
                    description:
                        'Official audio for Nicki Minaj "Big Foot", available everywhere now: https://NickiMinaj.lnk.to/BigFoot\n\n►Connect with Nicki 🎀🦄\nhttps://www.nickiminajofficial.com\nhttps://instagram.com/nickiminaj\nhttps://twitter.com/nickiminaj\nhttps://facebook.com/nickiminaj\nhttps://snapchat.com/add/nickiminaj\nhttps://tiktok.com/@nickiminaj\n\n►Shop Official Merch: https://shop.nickiminajofficial.com\n\n►Subscribe on YouTube: http://bit.ly/NickiMinajYTSub\n\n#NickiMinaj #BigFoot',
                },
            },
            contentDetails: {
                duration: "PT4M23S",
                dimension: "2d",
                definition: "hd",
                caption: "false",
                licensedContent: true,
                regionRestriction: { blocked: ["BY", "RU"] },
                contentRating: {},
                projection: "rectangular",
            },
            statistics: { viewCount: "1483075", likeCount: "95571", favoriteCount: "0", commentCount: "43056" },
        },
        {
            kind: "youtube#video",
            etag: "dxVjtSxEiS0P3YG4AY3RjKmnkEo",
            id: "hFQy0I3g8co",
            snippet: {
                publishedAt: "2024-01-29T03:35:25Z",
                channelId: "UCDVYQ4Zhbm3S2dlz7P1GBDg",
                title: "Detroit Lions vs. San Francisco 49ers Game Highlights | 2023 NFC Championship",
                description:
                    "Watch live local and primetime games, NFL RedZone, and NFL Network on Plus.NFL.com\n\nCheck out our other channels:\nNFL Mundo https://www.youtube.com/mundonfl\nNFL Brasil https://www.youtube.com/c/NFLBrasilOficial\nNFL UK https://www.youtube.com/channel/UCVe0dAja_vZCmvfHXjtdRQA \nNFL Fantasy Football https://www.youtube.com/nflfantasyfootball\nNFL Play Football https://www.youtube.com/playfootball\nNFL Throwback http://www.youtube.com/nflvault\nNFL Films http://www.youtube.com/nflfilms\nNFL Network http://www.youtube.com/nflnetwork\n\n#NFL #Football #AmericanFootball",
                thumbnails: {
                    default: { url: "https://i.ytimg.com/vi/hFQy0I3g8co/default.jpg", width: 120, height: 90 },
                    medium: { url: "https://i.ytimg.com/vi/hFQy0I3g8co/mqdefault.jpg", width: 320, height: 180 },
                    high: { url: "https://i.ytimg.com/vi/hFQy0I3g8co/hqdefault.jpg", width: 480, height: 360 },
                    standard: { url: "https://i.ytimg.com/vi/hFQy0I3g8co/sddefault.jpg", width: 640, height: 480 },
                    maxres: { url: "https://i.ytimg.com/vi/hFQy0I3g8co/maxresdefault.jpg", width: 1280, height: 720 },
                },
                channelTitle: "NFL",
                categoryId: "17",
                liveBroadcastContent: "none",
                localized: {
                    title: "Detroit Lions vs. San Francisco 49ers Game Highlights | 2023 NFC Championship",
                    description:
                        "Watch live local and primetime games, NFL RedZone, and NFL Network on Plus.NFL.com\n\nCheck out our other channels:\nNFL Mundo https://www.youtube.com/mundonfl\nNFL Brasil https://www.youtube.com/c/NFLBrasilOficial\nNFL UK https://www.youtube.com/channel/UCVe0dAja_vZCmvfHXjtdRQA \nNFL Fantasy Football https://www.youtube.com/nflfantasyfootball\nNFL Play Football https://www.youtube.com/playfootball\nNFL Throwback http://www.youtube.com/nflvault\nNFL Films http://www.youtube.com/nflfilms\nNFL Network http://www.youtube.com/nflnetwork\n\n#NFL #Football #AmericanFootball",
                },
            },
            contentDetails: {
                duration: "PT15M54S",
                dimension: "2d",
                definition: "hd",
                caption: "true",
                licensedContent: true,
                contentRating: {},
                projection: "rectangular",
            },
            statistics: { viewCount: "3418351", likeCount: "45998", favoriteCount: "0", commentCount: "7785" },
        },
        {
            kind: "youtube#video",
            etag: "nPyBhXHtLMd84Ofu1_hyv4nXPhE",
            id: "krsBRQbOPQ4",
            snippet: {
                publishedAt: "2024-01-27T17:00:00Z",
                channelId: "UCX6OQ3DkcsbYNE6H8uQQuVA",
                title: "$1 vs $250,000,000 Private Island!",
                description:
                    "Watch until the end to see how crazy the last island is \nPlay my ALL NEW MrBeast's Disco Dop level in Stumble Guys today! Download now and you could win $10K! https://stumbleguys.onelink.me/Zh4x/MrBeastYT\nNO PUR. NEC’Y. 18+. Ends 2/3/24. Terms apply: https://bit.ly/MrBeastSweepstakes_OfficialRules\n\nMusic Provided by https://www.extrememusic.com\n\nNew Merch - https://mrbeast.store\n\nCheck out Viewstats! - https://www.viewstats.com/\n\nSUBSCRIBE OR I TAKE YOUR DOG\n╔═╦╗╔╦╗╔═╦═╦╦╦╦╗╔═╗\n║╚╣║║║╚╣╚╣╔╣╔╣║╚╣═╣ \n╠╗║╚╝║║╠╗║╚╣║║║║║═╣\n╚═╩══╩═╩═╩═╩╝╚╩═╩═╝\n\nFor any questions or inquiries regarding this video, please reach out to chucky@mrbeastbusiness.com\n\n----------------------------------------------------------------\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n•  Im Hiring! - https://www.mrbeastjobs.com/\n\nNO PURCHASE NECESSARY. Open to US residents (excl. NY & FL; incl. DC), 18+ (19+ AL/NE; 21+ MS) at entry. Starts 1/27/24 at 12:00pm ET. Ends 2/3/24 at 11:59pm ET. To enter visit https://stumbleguys.onelink.me/Zh4x/MrBeastYT. Void where prohibited and outside US. Prize: one (1) $10k cash prize. Sponsor: MrBeastYouTube, LLC. Odds of winning depend on number of eligible entries rec’d. Other terms apply. See https://bit.ly/MrBeastSweepstakes_OfficialRules",
                thumbnails: {
                    default: { url: "https://i.ytimg.com/vi/krsBRQbOPQ4/default.jpg", width: 120, height: 90 },
                    medium: { url: "https://i.ytimg.com/vi/krsBRQbOPQ4/mqdefault.jpg", width: 320, height: 180 },
                    high: { url: "https://i.ytimg.com/vi/krsBRQbOPQ4/hqdefault.jpg", width: 480, height: 360 },
                    standard: { url: "https://i.ytimg.com/vi/krsBRQbOPQ4/sddefault.jpg", width: 640, height: 480 },
                    maxres: { url: "https://i.ytimg.com/vi/krsBRQbOPQ4/maxresdefault.jpg", width: 1280, height: 720 },
                },
                channelTitle: "MrBeast",
                categoryId: "24",
                liveBroadcastContent: "none",
                defaultLanguage: "en",
                localized: {
                    title: "$1 vs $250,000,000 Private Island!",
                    description:
                        "Watch until the end to see how crazy the last island is \nPlay my ALL NEW MrBeast's Disco Dop level in Stumble Guys today! Download now and you could win $10K! https://stumbleguys.onelink.me/Zh4x/MrBeastYT\nNO PUR. NEC’Y. 18+. Ends 2/3/24. Terms apply: https://bit.ly/MrBeastSweepstakes_OfficialRules\n\nMusic Provided by https://www.extrememusic.com\n\nNew Merch - https://mrbeast.store\n\nCheck out Viewstats! - https://www.viewstats.com/\n\nSUBSCRIBE OR I TAKE YOUR DOG\n╔═╦╗╔╦╗╔═╦═╦╦╦╦╗╔═╗\n║╚╣║║║╚╣╚╣╔╣╔╣║╚╣═╣ \n╠╗║╚╝║║╠╗║╚╣║║║║║═╣\n╚═╩══╩═╩═╩═╩╝╚╩═╩═╝\n\nFor any questions or inquiries regarding this video, please reach out to chucky@mrbeastbusiness.com\n\n----------------------------------------------------------------\nfollow all of these or i will kick you\n• Facebook - https://www.facebook.com/MrBeast6000/\n• Twitter - https://twitter.com/MrBeast\n•  Instagram - https://www.instagram.com/mrbeast\n•  Im Hiring! - https://www.mrbeastjobs.com/\n\nNO PURCHASE NECESSARY. Open to US residents (excl. NY & FL; incl. DC), 18+ (19+ AL/NE; 21+ MS) at entry. Starts 1/27/24 at 12:00pm ET. Ends 2/3/24 at 11:59pm ET. To enter visit https://stumbleguys.onelink.me/Zh4x/MrBeastYT. Void where prohibited and outside US. Prize: one (1) $10k cash prize. Sponsor: MrBeastYouTube, LLC. Odds of winning depend on number of eligible entries rec’d. Other terms apply. See https://bit.ly/MrBeastSweepstakes_OfficialRules",
                },
                defaultAudioLanguage: "en",
            },
            contentDetails: {
                duration: "PT16M59S",
                dimension: "2d",
                definition: "hd",
                caption: "true",
                licensedContent: true,
                contentRating: {},
                projection: "rectangular",
            },
            statistics: { viewCount: "67081954", likeCount: "3133255", favoriteCount: "0", commentCount: "73017" },
        },
        {
            kind: "youtube#video",
            etag: "ihMjuzmjxCPlNjeDDDdvElxGZCM",
            id: "qQlr9-rF32A",
            snippet: {
                publishedAt: "2024-01-28T20:35:42Z",
                channelId: "UCq7OHvWO6Z3u-LztFdrcU-g",
                title: "Despicable Me 4 | Official Trailer",
                description:
                    "Things just got a little more despicable. DM4 hits theaters July 3. \n--\nTikTok: https://www.tiktok.com/@minions\r\nFacebook:  https://uni.pictures/MinionsFB\r\nX: https://uni.pictures/MinionsTW\r\nInstagram:  https://uni.pictures/MinionsIG\nOfficial Site:  https://despicable.me\r\n--\nIn the first Despicable Me movie in seven years, Gru, the world’s favorite supervillain-turned-Anti-Villain League-agent, returns for an exciting, bold new era of Minions mayhem in Illumination’s Despicable Me 4. \n\nFollowing the 2022 summer blockbuster phenomenon of Illumination’s Minions: The Rise of Gru, which earned almost $1 billion worldwide, the biggest global animated franchise in history now begins a new chapter as Gru (Oscar® nominee Steve Carrell) and Lucy (Oscar® nominee Kristen Wiig) and their girls —Margo (Miranda Cosgrove), Edith (Dana Gaier) and Agnes (Madison Polan)—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad.\n\nGru faces a new nemesis in Maxime Le Mal (Emmy winner Will Ferrell) and his femme fatale girlfriend Valentina (Emmy nominee Sofia Vergara), and the family is forced to go on the run.  \n\nThe film features fresh new characters voiced by Joey King (Bullet Train), Emmy winner Stephen Colbert (The Late Show with Stephen Colbert) and Chloe Fineman (Saturday Night Live). Pierre Coffin returns as the iconic voice of the Minions and Oscar® nominee Steve Coogan returns as Silas Ramsbottom. \n\nPacked with non-stop action and filled with Illumination’s signature subversive humor, Despicable Me 4 is directed by a co-creator of the Minions, Oscar® nominee Chris Renaud (Despicable Me, The Secret Life of Pets), and is produced by Illumination’s visionary founder and CEO Chris Meledandri and by Brett Hoffman (executive producer, The Super Mario Bros. Movie and Minions: The Rise of Gru). The film is co-directed by Patrick Delage (animation director Sing 2 and The Secret Life of Pets 2), and the screenplay is by the Emmy winning creator of White Lotus, Mike White, and the veteran writer of every Despicable Me film, Ken Daurio.",
                thumbnails: {
                    default: { url: "https://i.ytimg.com/vi/qQlr9-rF32A/default.jpg", width: 120, height: 90 },
                    medium: { url: "https://i.ytimg.com/vi/qQlr9-rF32A/mqdefault.jpg", width: 320, height: 180 },
                    high: { url: "https://i.ytimg.com/vi/qQlr9-rF32A/hqdefault.jpg", width: 480, height: 360 },
                    standard: { url: "https://i.ytimg.com/vi/qQlr9-rF32A/sddefault.jpg", width: 640, height: 480 },
                    maxres: { url: "https://i.ytimg.com/vi/qQlr9-rF32A/maxresdefault.jpg", width: 1280, height: 720 },
                },
                channelTitle: "Illumination",
                tags: [
                    "Minions",
                    "Movie",
                    "Trailer",
                    "Despicable Me",
                    "banana",
                    "kevin",
                    "bob",
                    "official",
                    "Minion",
                    "stuart",
                    "Illumination",
                    "Illumination Entertainment",
                    "minions",
                    "movie clip",
                    "minionnation",
                    "Gru",
                    "Animated Movie",
                    "Family Film",
                    "Animation",
                    "Steve Carell",
                    "Kristen Wiig",
                    "Family Fun",
                    "Comedy",
                    "Adventure",
                    "Kids Movie",
                    "Villain",
                    "Banana",
                    "Super Villain",
                    "Funny",
                    "Children's Film",
                    "3D Animation",
                    "Cute Characters",
                    "Gru's Lab",
                    "Minion Madness",
                    "Mischievous",
                    "Animated Comedy",
                    "Despicable Me Trailer",
                ],
                categoryId: "24",
                liveBroadcastContent: "none",
                localized: {
                    title: "Despicable Me 4 | Official Trailer",
                    description:
                        "Things just got a little more despicable. DM4 hits theaters July 3. \n--\nTikTok: https://www.tiktok.com/@minions\r\nFacebook:  https://uni.pictures/MinionsFB\r\nX: https://uni.pictures/MinionsTW\r\nInstagram:  https://uni.pictures/MinionsIG\nOfficial Site:  https://despicable.me\r\n--\nIn the first Despicable Me movie in seven years, Gru, the world’s favorite supervillain-turned-Anti-Villain League-agent, returns for an exciting, bold new era of Minions mayhem in Illumination’s Despicable Me 4. \n\nFollowing the 2022 summer blockbuster phenomenon of Illumination’s Minions: The Rise of Gru, which earned almost $1 billion worldwide, the biggest global animated franchise in history now begins a new chapter as Gru (Oscar® nominee Steve Carrell) and Lucy (Oscar® nominee Kristen Wiig) and their girls —Margo (Miranda Cosgrove), Edith (Dana Gaier) and Agnes (Madison Polan)—welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad.\n\nGru faces a new nemesis in Maxime Le Mal (Emmy winner Will Ferrell) and his femme fatale girlfriend Valentina (Emmy nominee Sofia Vergara), and the family is forced to go on the run.  \n\nThe film features fresh new characters voiced by Joey King (Bullet Train), Emmy winner Stephen Colbert (The Late Show with Stephen Colbert) and Chloe Fineman (Saturday Night Live). Pierre Coffin returns as the iconic voice of the Minions and Oscar® nominee Steve Coogan returns as Silas Ramsbottom. \n\nPacked with non-stop action and filled with Illumination’s signature subversive humor, Despicable Me 4 is directed by a co-creator of the Minions, Oscar® nominee Chris Renaud (Despicable Me, The Secret Life of Pets), and is produced by Illumination’s visionary founder and CEO Chris Meledandri and by Brett Hoffman (executive producer, The Super Mario Bros. Movie and Minions: The Rise of Gru). The film is co-directed by Patrick Delage (animation director Sing 2 and The Secret Life of Pets 2), and the screenplay is by the Emmy winning creator of White Lotus, Mike White, and the veteran writer of every Despicable Me film, Ken Daurio.",
                },
                defaultAudioLanguage: "en-US",
            },
            contentDetails: {
                duration: "PT2M27S",
                dimension: "2d",
                definition: "hd",
                caption: "true",
                licensedContent: false,
                contentRating: {},
                projection: "rectangular",
            },
            statistics: { viewCount: "2998450", likeCount: "108994", favoriteCount: "0", commentCount: "0" },
        },
        {
            kind: "youtube#video",
            etag: "mcj83oimXIFDDP2sQW9kj1YgT5A",
            id: "5r3RxHoZEyQ",
            snippet: {
                publishedAt: "2024-01-28T23:00:09Z",
                channelId: "UC_ntXHv-XdKCD7CPynVvnQw",
                title: "DRAGON BALL: Sparking! ZERO - Goku VS Vegeta - Rivals Trailer [BUDOKAI TENKAICHI Series]",
                description:
                    "This rivalry goes way back. Now let's take it to the next level.\nGoku and Vegeta are back in DRAGON BALL: Sparking! ZERO. #dbsz \n\nLearn more: https://bnent.eu/DBSZ-CharactersReveal \n\nWishlist now: http://bnent.eu/DBSparkingZero\n\nFollow Dragon Ball Games on social media:\nX: https://twitter.com/dragonballgames\nInstagram: https://www.instagram.com/dragonballgames\nFacebook: https://www.facebook.com/DBZ.videogamesUS/",
                thumbnails: {
                    default: { url: "https://i.ytimg.com/vi/5r3RxHoZEyQ/default.jpg", width: 120, height: 90 },
                    medium: { url: "https://i.ytimg.com/vi/5r3RxHoZEyQ/mqdefault.jpg", width: 320, height: 180 },
                    high: { url: "https://i.ytimg.com/vi/5r3RxHoZEyQ/hqdefault.jpg", width: 480, height: 360 },
                    standard: { url: "https://i.ytimg.com/vi/5r3RxHoZEyQ/sddefault.jpg", width: 640, height: 480 },
                    maxres: { url: "https://i.ytimg.com/vi/5r3RxHoZEyQ/maxresdefault.jpg", width: 1280, height: 720 },
                },
                channelTitle: "Bandai Namco Entertainment America",
                tags: [
                    "Bandai Namco",
                    "Bandai Namco Entertainment",
                    "Video",
                    "Games",
                    "video games",
                    "namco bandai",
                    "United States",
                    "PS5",
                    "PS4",
                    "Xbox Series X",
                ],
                categoryId: "20",
                liveBroadcastContent: "none",
                defaultLanguage: "en-US",
                localized: {
                    title: "DRAGON BALL: Sparking! ZERO - Goku VS Vegeta - Rivals Trailer [BUDOKAI TENKAICHI Series]",
                    description:
                        "This rivalry goes way back. Now let's take it to the next level.\nGoku and Vegeta are back in DRAGON BALL: Sparking! ZERO. #dbsz \n\nLearn more: https://bnent.eu/DBSZ-CharactersReveal \n\nWishlist now: http://bnent.eu/DBSparkingZero\n\nFollow Dragon Ball Games on social media:\nX: https://twitter.com/dragonballgames\nInstagram: https://www.instagram.com/dragonballgames\nFacebook: https://www.facebook.com/DBZ.videogamesUS/",
                },
                defaultAudioLanguage: "en",
            },
            contentDetails: {
                duration: "PT2M13S",
                dimension: "2d",
                definition: "hd",
                caption: "false",
                licensedContent: true,
                contentRating: {},
                projection: "rectangular",
            },
            statistics: { viewCount: "1418028", likeCount: "117027", favoriteCount: "0", commentCount: "9871" },
        },
    ],
    nextPageToken: "CAUQAA",
    pageInfo: { totalResults: 200, resultsPerPage: 5 },
};
